version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      minor-patch:
        patterns:
          - '*'
        update-types:
          - minor
          - patch
      aws-cdk:
        patterns:
          - aws-cdk
          - aws-cdk-lib
          - constructs
    commit-message:
      prefix: deps

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      github-actions:
        patterns:
          - '*'
    commit-message:
      prefix: ci
